/* Generated by prepare_rom.py; rebuild MCU firmware after changes. */
#ifndef ROM_REFERENCE_H
#define ROM_REFERENCE_H
#define ROM_START 0x1000U
#define ROM_LENGTH 350U
#define ROM_EXPECTED_SUM 0x9093U
#endif
