"""Создать образ ПЗУ 16 Кбайт и эталон суммы для варианта 11.
Без --input: демонстрационные байты 00..FF,00..5D в области 1000h..115Dh.
С --input: эталон по доверенному полному образу 16384 байта.
"""
from pathlib import Path
import argparse
SIZE, START, LENGTH = 16384, 0x1000, 350

def reference(data):
    if len(data) != SIZE:
        raise ValueError('Образ 27C128 должен содержать ровно 16384 байта')
    return sum(data[START:START + LENGTH]) & 0xFFFF

def demo():
    data = bytearray([0xFF]) * SIZE
    data[START:START + LENGTH] = bytes(i & 0xFF for i in range(LENGTH))
    return bytes(data)

def generate(data, out):
    check = reference(data)
    out.mkdir(parents=True, exist_ok=True)
    (out / 'rom27c128.bin').write_bytes(data)
    (out / 'rom_reference.h').write_text(
        '/* Generated by prepare_rom.py; rebuild MCU firmware after changes. */\n'
        '#ifndef ROM_REFERENCE_H\n#define ROM_REFERENCE_H\n'
        f'#define ROM_START 0x{START:04X}U\n#define ROM_LENGTH {LENGTH}U\n'
        f'#define ROM_EXPECTED_SUM 0x{check:04X}U\n#endif\n', encoding='ascii')
    print(f'ROM: {SIZE} bytes; range: {START:04X}..{START+LENGTH-1:04X}; sum: 0x{check:04X}')

if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--input', type=Path, help='Доверенный образ всего ПЗУ 16 Кбайт')
    p.add_argument('--out-dir', type=Path, default=Path(__file__).resolve().parent)
    a = p.parse_args()
    generate(a.input.read_bytes() if a.input else demo(), a.out_dir)
